"use client";

import { useMemo, useState } from "react";
import { ArrowRight, Check, Clock3, Code2, FilePlus2, Loader2, RefreshCw, Terminal, Zap } from "lucide-react";
import { clsx } from "clsx";
import type { DreamEdit, DreamRun } from "@/app/lib/types";

type Props = { initialEdits: DreamEdit[]; initialRuns: DreamRun[]; source: "notion" | "demo" };
type FilterId = "changed" | "skipped" | "all";
type SeededPage = { id: string; title: string; url?: string };

export function ReviewBoard({ initialEdits, initialRuns, source }: Props) {
  const [filter, setFilter] = useState<FilterId>("changed");
  const [topBusy, setTopBusy] = useState<"refresh" | "trigger" | "seed" | null>(null);
  const [seedResult, setSeedResult] = useState<string | null>(null);
  const [seededPages, setSeededPages] = useState<SeededPage[]>([]);
  const changedCount = initialEdits.filter((e) => e.status === "changed").length;
  const skippedCount = initialEdits.filter((e) => e.status === "skipped").length;
  const visible = useMemo(() => filter === "all" ? initialEdits : initialEdits.filter((e) => e.status === filter), [filter, initialEdits]);
  const lastRun = initialRuns[0];
  async function fakeRun() { setTopBusy("trigger"); await new Promise((r) => setTimeout(r, 800)); setTopBusy(null); }
  async function fakeRefresh() { setTopBusy("refresh"); await new Promise((r) => setTimeout(r, 500)); setTopBusy(null); }
  async function seedFastclipPages() {
    setTopBusy("seed");
    setSeedResult(null);
    try {
      const response = await fetch("/api/seed-fastclip", { method: "POST" });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error ?? "Failed to create pages");
      setSeededPages(data.created ?? []);
      setSeedResult(`Created ${data.created.length} fastclip.it pages in Notion`);
    } catch (error) {
      setSeedResult(error instanceof Error ? error.message : "Failed to create pages");
    } finally {
      setTopBusy(null);
    }
  }
  return <div className="min-h-screen bg-paper text-ink">
    <header className="sticky top-0 z-20 border-b border-line bg-paper/85 backdrop-blur"><div className="mx-auto flex max-w-[1480px] items-center justify-between gap-6 px-8 py-3.5"><div className="flex items-center gap-3"><Logo/><div className="flex flex-wrap items-center gap-2.5"><span className="text-[14px] font-semibold tracking-tight sm:text-[15px]">Notion Dreams | Command Center</span><span className="hidden h-4 w-px bg-line sm:block"/><span className="rounded-md border border-line bg-white px-2 py-1 font-mono text-[10px] uppercase tracking-[0.16em] text-mute">notion worker</span></div></div><div className="hidden items-center gap-7 md:flex"><TopStat k="changed" v={changedCount}/><TopStat k="skipped" v={skippedCount}/><TopStat k="last run" v={lastRun ? relativeFromNow(lastRun.ran_at) : "—"} mono/></div><div className="flex items-center gap-2"><button onClick={seedFastclipPages} disabled={topBusy!==null} className="inline-flex h-8 items-center gap-1.5 rounded-md border border-line bg-white px-2.5 text-[12px] font-medium text-ink transition-colors hover:bg-paper2 disabled:opacity-50">{topBusy==="seed" ? <Loader2 size={13} className="animate-spin"/> : <FilePlus2 size={13}/>}Seed pages</button><button onClick={fakeRefresh} disabled={topBusy!==null} className="inline-flex h-8 items-center gap-1.5 rounded-md border border-line bg-white px-2.5 text-[12px] font-medium text-ink transition-colors hover:bg-paper2 disabled:opacity-50"><RefreshCw size={13} className={topBusy==="refresh" ? "animate-spin" : ""}/>Refresh</button><button onClick={fakeRun} disabled={topBusy!==null} className="inline-flex h-8 items-center gap-1.5 rounded-md bg-ink px-3 text-[12px] font-medium text-paper transition-colors hover:bg-black disabled:opacity-60">{topBusy==="trigger" ? <Loader2 size={13} className="animate-spin"/> : <Zap size={12}/>} {topBusy==="trigger" ? "Dreaming…" : "Trigger dream"}</button></div></div></header>
    <main className="mx-auto max-w-[1480px] px-8 pb-24 pt-8">{seedResult&&<SeedNotice message={seedResult} pages={seededPages}/>}<div className="grid grid-cols-12 items-end gap-10"><div className="col-span-12 lg:col-span-8"><div className="font-mono text-[10px] uppercase tracking-[0.18em] text-mute">background editor · worker</div><h1 className="mt-3 max-w-3xl text-[44px] font-semibold leading-[1.05] tracking-tight">Your Notion pages read better after you sleep.</h1><p className="mt-3 max-w-xl text-[14.5px] leading-[1.6] text-mute">A scheduled Worker scans pages changed since the last run, removes filler, tightens wording, preserves meaning, and writes a full audit report under Dreams/date-time-report.</p></div><div className="col-span-12 lg:col-span-4"><Cadence changedCount={changedCount} skippedCount={skippedCount} source={source}/></div></div><div className="mt-12 grid grid-cols-12 gap-10"><aside className="col-span-12 lg:col-span-3"><RunHistory runs={initialRuns}/></aside><section className="col-span-12 lg:col-span-9"><div className="flex items-end justify-between border-b border-line pb-3"><div className="flex items-baseline gap-3"><h2 className="text-[15px] font-semibold tracking-tight">Dream edits</h2><span className="font-mono text-[11px] text-mute">{visible.length} shown</span></div><FilterTabs value={filter} onChange={setFilter} counts={{changed:changedCount, skipped:skippedCount, all:initialEdits.length}}/></div><div className="mt-6 flex flex-col gap-6">{visible.length>0 ? visible.map((edit)=><EditRow key={edit.id} edit={edit}/>) : <EmptyState/>}</div></section></div></main></div>;
}
function TopStat({k,v,mono=false}:{k:string;v:string|number;mono?:boolean}){return <div className="flex items-baseline gap-2"><span className="font-mono text-[10px] uppercase tracking-[0.14em] text-mute">{k}</span><span className={clsx("text-[13px] font-semibold tabular-nums", mono && "font-mono")}>{v}</span></div>}
function Logo(){return <div className="flex h-7 w-7 items-center justify-center rounded-md border border-line bg-white"><svg width="14" height="14" viewBox="0 0 14 14" fill="none"><circle cx="7" cy="7" r="6" stroke="#111714" strokeWidth="1.4"/><path d="M4 8.2c2.2.9 4.1-.4 4.7-3.2 1.1 1.4 1.4 3.9-.2 5.2-1.4 1.1-3.6.7-4.5-2Z" stroke="#4F7A5C" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/></svg></div>}
function Cadence({changedCount,skippedCount,source}:{changedCount:number;skippedCount:number;source:"notion"|"demo"}){return <div className="grid grid-cols-2 gap-px overflow-hidden rounded-xl border border-line bg-line"><CadenceCell label="changed" value={changedCount} accent="moss"/><CadenceCell label="skipped" value={skippedCount} accent="amber"/><CadenceCell label="data" value={source} mono/><CadenceCell label="worker" value="healthy" accent="moss"/></div>}
function CadenceCell({label,value,accent,mono}:{label:string;value:string|number;accent?:"amber"|"moss";mono?:boolean}){const dot=accent==="amber"?"bg-amber":accent==="moss"?"bg-moss":"bg-mute2";return <div className="bg-white p-4"><div className="flex items-center gap-1.5 font-mono text-[10px] uppercase tracking-[0.14em] text-mute"><span className={clsx("h-1.5 w-1.5 rounded-full",dot)}/>{label}</div><div className={clsx("mt-2 text-[26px] font-semibold tabular-nums",mono&&"font-mono text-[20px]")}>{value}</div></div>}
function FilterTabs({value,onChange,counts}:{value:FilterId;onChange:(v:FilterId)=>void;counts:Record<FilterId,number>}){const opts:{id:FilterId;label:string}[]=[{id:"changed",label:"Changed"},{id:"skipped",label:"Skipped"},{id:"all",label:"All"}];return <div className="flex items-center gap-1 rounded-md border border-line bg-white p-0.5">{opts.map((o)=>{const active=value===o.id;return <button key={o.id} onClick={()=>onChange(o.id)} className={clsx("inline-flex h-7 items-center gap-1.5 rounded px-2.5 text-[12px] font-medium transition-colors",active?"bg-ink text-paper":"text-mute hover:text-ink")}>{o.label}<span className={clsx("font-mono text-[10px]",active?"text-paper/70":"text-mute2")}>{counts[o.id]}</span></button>})}</div>}
function RunHistory({runs}:{runs:DreamRun[]}){return <div className="lg:sticky lg:top-[68px]"><div className="border-b border-line pb-3"><div className="flex items-baseline justify-between gap-3"><h2 className="text-[15px] font-semibold tracking-tight">Worker runs</h2><span className="font-mono text-[10px] tabular-nums text-mute">{runs.length}/1000</span></div><p className="mt-1 font-mono text-[11px] text-mute">Notion Worker · manual trigger</p></div><ol className="mt-5 flex flex-col pr-2">{runs.map((r,i)=>{const source=runSourceMeta(r.source);const Icon=source.icon;return <li key={r.key} className="relative grid grid-cols-[26px_1fr] gap-3 pb-5">{i<runs.length-1&&<span className="absolute left-[12px] top-5 h-full w-px bg-line"/>}<span className={clsx("relative z-10 mt-0.5 flex h-6 w-6 items-center justify-center rounded-full ring-4 ring-paper",source.dot)}><Icon size={12} strokeWidth={2.3} className="text-white"/></span><div className="min-w-0"><div className="grid grid-cols-[auto_minmax(0,1fr)] items-start gap-2"><span className="font-mono text-[11px] tabular-nums text-ink">{fmtClock(r.ran_at)}</span><span className={clsx("justify-self-end rounded px-1.5 py-0.5 text-right font-mono text-[9.5px] leading-tight tracking-[0.04em]",source.badge)}>{source.label}</span></div><div className="mt-0.5 text-[12.5px] text-mute"><span><span className="font-semibold text-ink tabular-nums">{r.blocks_changed ?? 0}</span> blocks changed</span></div></div></li>})}</ol></div>}
function runSourceMeta(source?:string){const normalized=(source??"worker").toLowerCase();if(normalized.includes("scheduled")){return{label:"Scheduled",dot:"bg-moss",badge:"bg-mossSoft text-moss",icon:Clock3}}if(normalized.includes("manual")){return{label:"Manual CLI",dot:"bg-amber",badge:"bg-amberSoft text-amber",icon:Terminal}}return{label:"Deploy",dot:"bg-mute",badge:"bg-paper2 text-mute",icon:Code2}}
function EditRow({edit}:{edit:DreamEdit}){return <article className="overflow-hidden rounded-xl border border-line bg-white"><header className="flex flex-wrap items-start justify-between gap-6 border-b border-line px-6 pb-4 pt-5"><div><div className="flex items-center gap-2.5"><h3 className="truncate text-[17px] font-semibold tracking-tight">{edit.page}</h3><StatusPill status={edit.status}/></div><div className="mt-1 flex items-center gap-2 font-mono text-[11.5px] text-mute"><span>{edit.path}</span><span className="text-line">·</span><span>{edit.block_type}</span></div></div></header><div className="grid grid-cols-12 gap-0 lg:divide-x lg:divide-line"><div className="col-span-12 px-6 py-5 lg:col-span-6"><TextPanel title="Before" body={edit.before_text} muted/></div><div className="col-span-12 border-t border-line px-6 py-5 lg:col-span-6 lg:border-t-0"><TextPanel title="After" body={edit.after_text}/><div className="mt-4 rounded-md bg-paper2 px-3.5 py-3"><div className="font-mono text-[10px] uppercase tracking-[0.14em] text-mute">Dream reason</div><p className="mt-1.5 text-[13px] leading-[1.6] text-ink">{edit.edit_reason}</p></div></div></div></article>}
function StatusPill({status}:{status:string}){const cfg=status==="changed"?{label:"changed",cls:"bg-mossSoft text-moss",dot:"bg-moss"}:status==="skipped"?{label:"skipped",cls:"bg-paper2 text-mute",dot:"bg-mute2"}:{label:"pending",cls:"bg-amberSoft text-amber",dot:"bg-amber"};return <span className={clsx("inline-flex items-center gap-1.5 rounded-full px-2 py-0.5 font-mono text-[10px] uppercase tracking-[0.12em]",cfg.cls)}><span className={clsx("h-1.5 w-1.5 rounded-full",cfg.dot)}/>{cfg.label}</span>}
function TextPanel({title,body,muted=false}:{title:string;body:string;muted?:boolean}){return <div><div className="font-mono text-[10px] uppercase tracking-[0.14em] text-mute">{title}</div><p className={clsx("mt-2 rounded-md border border-line p-3.5 text-[13.5px] leading-[1.65]",muted?"bg-paper text-mute":"bg-white text-ink")}>{body}</p></div>}
function SeedNotice({message,pages}:{message:string;pages:SeededPage[]}){return <div className="mb-5 rounded-md border border-line bg-white px-4 py-3 text-[13px] text-ink shadow-soft"><div className="font-medium">{message}</div>{pages.length>0&&<div className="mt-2 flex flex-wrap gap-2">{pages.map((page)=>page.url?<a key={page.id} href={page.url} target="_blank" rel="noreferrer" className="rounded border border-line bg-paper px-2 py-1 font-mono text-[11px] text-mute hover:text-ink">{page.title}</a>:<span key={page.id} className="rounded border border-line bg-paper px-2 py-1 font-mono text-[11px] text-mute">{page.title}</span>)}</div>}</div>}
function EmptyState(){return <div className="rounded-xl border border-dashed border-line bg-white px-6 py-10 text-center"><div className="text-[15px] font-semibold tracking-tight">No edit examples yet</div><p className="mx-auto mt-2 max-w-md text-[13px] leading-[1.6] text-mute">The dashboard is reading live worker reports. Current reports are hello-world runs, so they only populate run history until the polishing worker starts changing blocks.</p></div>}
function relativeFromNow(value?:string){if(!value)return"—";const diff=Math.max(0,Date.now()-new Date(value).getTime());const min=Math.floor(diff/60000);if(min<1)return"now";if(min<60)return`${min}m ago`;return`${Math.floor(min/60)}h ago`}
function fmtClock(value?:string){if(!value)return"—";return new Date(value).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}
